// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# SharePoint subset of the Microsoft Graph v1.0 OpenAPI specification (generated from graphexplorer.yaml).
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://graph.microsoft.com/v1.0/sites") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # List baseSitePages
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages(map<string|string[]> headers = {}, *SitesListPagesQueries queries) returns MicrosoftGraphBaseSitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a page in the site pages list of a site
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    resource isolated function post [string siteId]/pages(MicrosoftGraphBaseSitePage payload, map<string|string[]> headers = {}) returns MicrosoftGraphBaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId](map<string|string[]> headers = {}, *SitesGetPagesQueries queries) returns MicrosoftGraphBaseSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete baseSitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId](SitesDeletePagesHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property pages in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId](MicrosoftGraphBaseSitePage payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/createdByUser(map<string|string[]> headers = {}, *SitesPagesGetCreatedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/createdByUser/mailboxSettings(map<string|string[]> headers = {}, *SitesPagesCreatedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/createdByUser/mailboxSettings(MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/createdByUser/serviceProvisioningErrors(map<string|string[]> headers = {}, *SitesPagesCreatedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/createdByUser/serviceProvisioningErrors/\$count(map<string|string[]> headers = {}, *SitesPagesCreatedByUserServiceProvisioningErrorsGetCount7e89Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/lastModifiedByUser(map<string|string[]> headers = {}, *SitesPagesGetLastModifiedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/lastModifiedByUser/mailboxSettings(map<string|string[]> headers = {}, *SitesPagesLastModifiedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/lastModifiedByUser/mailboxSettings(MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/lastModifiedByUser/serviceProvisioningErrors(map<string|string[]> headers = {}, *SitesPagesLastModifiedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/lastModifiedByUser/serviceProvisioningErrors/\$count(map<string|string[]> headers = {}, *SitesPagesLastModifiedByUserServiceProvisioningErrorsGetCount6cf6Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage(map<string|string[]> headers = {}, *SitesGetPagesAsSitePageQueries queries) returns MicrosoftGraphSitePage|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get canvasLayout from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout(map<string|string[]> headers = {}, *SitesPagesAsSitePageGetCanvasLayoutQueries queries) returns MicrosoftGraphCanvasLayout|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property canvasLayout for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout(SitesPagesAsSitePageDeleteCanvasLayoutHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property canvasLayout in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout(MicrosoftGraphCanvasLayout payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutListHorizontalSectionsQueries queries) returns MicrosoftGraphHorizontalSectionCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections(MicrosoftGraphHorizontalSection payload, map<string|string[]> headers = {}) returns MicrosoftGraphHorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get horizontalSections from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId](map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutGetHorizontalSectionsQueries queries) returns MicrosoftGraphHorizontalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property horizontalSections for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId](SitesPagesAsSitePageCanvasLayoutDeleteHorizontalSectionsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property horizontalSections in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId](MicrosoftGraphHorizontalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsListColumnsQueries queries) returns MicrosoftGraphHorizontalSectionColumnCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns(MicrosoftGraphHorizontalSectionColumn payload, map<string|string[]> headers = {}) returns MicrosoftGraphHorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get columns from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId](map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsGetColumnsQueries queries) returns MicrosoftGraphHorizontalSectionColumn|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property columns for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId](SitesPagesAsSitePageCanvasLayoutHorizontalSectionsDeleteColumnsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property columns in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId](MicrosoftGraphHorizontalSectionColumn payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsListWebpartsQueries queries) returns MicrosoftGraphWebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts(MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts/[string webPartId](map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetWebpartsQueries queries) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts/[string webPartId](SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsDeleteWebpartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts/[string webPartId](MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts/[string webPartId]/microsoft\.graph\.getPositionOfWebPart(map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + horizontalSectionColumnId - The unique identifier of horizontalSectionColumn
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/[string horizontalSectionColumnId]/webparts/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsWebpartsGetCountBbb9Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/${getEncodedUri(horizontalSectionColumnId)}/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + horizontalSectionId - The unique identifier of horizontalSection
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/[string horizontalSectionId]/columns/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsColumnsGetCount9382Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/${getEncodedUri(horizontalSectionId)}/columns/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/horizontalSections/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutHorizontalSectionsGetCount38fcQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/horizontalSections/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get verticalSection from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutGetVerticalSectionQueries queries) returns MicrosoftGraphVerticalSection|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property verticalSection for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection(SitesPagesAsSitePageCanvasLayoutDeleteVerticalSectionHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property verticalSection in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection(MicrosoftGraphVerticalSection payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutVerticalSectionListWebpartsQueries queries) returns MicrosoftGraphWebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts(MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webparts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts/[string webPartId](map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutVerticalSectionGetWebpartsQueries queries) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete navigation property webparts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts/[string webPartId](SitesPagesAsSitePageCanvasLayoutVerticalSectionDeleteWebpartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webparts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts/[string webPartId](MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts/[string webPartId]/microsoft\.graph\.getPositionOfWebPart(map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/canvasLayout/verticalSection/webparts/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageCanvasLayoutVerticalSectionWebpartsGetCount185fQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/canvasLayout/verticalSection/webparts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get createdByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/createdByUser(map<string|string[]> headers = {}, *SitesPagesAsSitePageGetCreatedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/createdByUser/mailboxSettings(map<string|string[]> headers = {}, *SitesPagesAsSitePageCreatedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/createdByUser/mailboxSettings(MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/createdByUser/serviceProvisioningErrors(map<string|string[]> headers = {}, *SitesPagesAsSitePageCreatedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/createdByUser/serviceProvisioningErrors/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageCreatedByUserServiceProvisioningErrorsGetCountA4bdQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/createdByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get lastModifiedByUser from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/lastModifiedByUser(map<string|string[]> headers = {}, *SitesPagesAsSitePageGetLastModifiedByUserQueries queries) returns MicrosoftGraphUser|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get mailboxSettings property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Entity result 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/lastModifiedByUser/mailboxSettings(map<string|string[]> headers = {}, *SitesPagesAsSitePageLastModifiedByUserGetMailboxSettingsQueries queries) returns MicrosoftGraphMailboxSettings|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update property mailboxSettings value.
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/lastModifiedByUser/mailboxSettings(MicrosoftGraphMailboxSettings payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/mailboxSettings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Get serviceProvisioningErrors property value
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/lastModifiedByUser/serviceProvisioningErrors(map<string|string[]> headers = {}, *SitesPagesAsSitePageLastModifiedByUserListServiceProvisioningErrorsQueries queries) returns MicrosoftGraphServiceProvisioningErrorCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/lastModifiedByUser/serviceProvisioningErrors/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageLastModifiedByUserServiceProvisioningErrorsGetCount9ea6Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/lastModifiedByUser/serviceProvisioningErrors/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts(map<string|string[]> headers = {}, *SitesPagesAsSitePageListWebPartsQueries queries) returns MicrosoftGraphWebPartCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create new navigation property to webParts for sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property 
    # + return - Created navigation property 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts(MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get webParts from sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved navigation property 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts/[string webPartId](map<string|string[]> headers = {}, *SitesPagesAsSitePageGetWebPartsQueries queries) returns MicrosoftGraphWebPart|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<Encoding> queryParamEncoding = {"$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete webPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function delete [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts/[string webPartId](SitesPagesAsSitePageDeleteWebPartsHeaders headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update the navigation property webParts in sites
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + payload - New navigation property values 
    # + return - Success 
    resource isolated function patch [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts/[string webPartId](MicrosoftGraphWebPart payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # Invoke action getPositionOfWebPart
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + webPartId - The unique identifier of webPart
    # + headers - Headers to be sent with the request 
    # + return - Success 
    resource isolated function post [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts/[string webPartId]/microsoft\.graph\.getPositionOfWebPart(map<string|string[]> headers = {}) returns WebPartPositionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/${getEncodedUri(webPartId)}/microsoft.graph.getPositionOfWebPart`;
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + baseSitePageId - The unique identifier of baseSitePage
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/[string baseSitePageId]/microsoft\.graph\.sitePage/webParts/\$count(map<string|string[]> headers = {}, *SitesPagesAsSitePageWebPartsGetCountEb99Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/${getEncodedUri(baseSitePageId)}/microsoft.graph.sitePage/webParts/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/\$count(map<string|string[]> headers = {}, *SitesPagesGetCount3155Queries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get SitePage
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Retrieved collection 
    resource isolated function get [string siteId]/pages/microsoft\.graph\.sitePage(map<string|string[]> headers = {}, *SitesListPagesAsSitePageQueries queries) returns MicrosoftGraphSitePageCollectionResponse|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage`;
        map<Encoding> queryParamEncoding = {"$orderby": {style: FORM, explode: false}, "$select": {style: FORM, explode: false}, "$expand": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get the number of the resource
    #
    # + siteId - The unique identifier of site
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The count of the resource 
    resource isolated function get [string siteId]/pages/microsoft\.graph\.sitePage/\$count(map<string|string[]> headers = {}, *SitesPagesGetCountAsSitePageC4edQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(siteId)}/pages/microsoft.graph.sitePage/$count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }
}
